[package]
name = "snag"
version = "0.1.0"
edition = "2021"
authors = ["Gbubemi Smith <gsmithwalter@gmail.com>"]

[lib]
path = "src/cli.rs"

[[bin]]
path = "src/main.rs"
name = "snag"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
